### ISSUE TITLE
这玩意比我那破程序牛逼多了

### ISSUE THREAD

**Issue by ice1000** [ProgramLeague/InstruSniffer#2]
我的那玩意其实就是瞎JB整的，你这玩意弄完可以考虑整个爬虫库出来

**Comment by ice1000** [comment]
另外，爬虫算法如果采用朴素的搜索的话都是广度优先的，或者迭代加深。单纯深搜的话，我总觉得要StackOverflow。。

请百度“BFS”或者“迭代加深搜索”。进阶的话，“A星搜索”（其实很简单个玩意，就看你会不会写评估函数

**Comment by Ray-Eldath** [comment]
**好牛逼的样子**
看来我得认真学习一下
我先用Webmagic凑合着。。。等弄完我再自己写
